name: Preprocess Dataset

on:
  push:
    paths:
      - 'preprocessing/automate_Usamah-Putra-Firdaus.py'
      - 'diabetes_prediction_raw.csv'

jobs:
  preprocess:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy matplotlib seaborn scikit-learn

      - name: Run preprocessing
        run: |
          python preprocessing/automate_Usamah-Putra-Firdaus.py

      - name: Upload processed dataset
        uses: actions/upload-artifact@v4
        with:
          name: processed-dataset
          path: preprocessing/diabetes_prediction_preprocessing.csv
